# Dockerfile.test-tools - Pre-built test tools for Docker container repos
#
# Contains: ShellCheck, Hadolint, Bats (with bats-support + bats-assert + bats-mock)
#
# Usage:
#   docker build -t test-tools:local -f template/dockerfile/Dockerfile.test-tools .
#   Then in repo Dockerfile:
#     COPY --from=test-tools:local /usr/local/bin/shellcheck /usr/local/bin/shellcheck

FROM bats/bats:latest AS bats-src

FROM alpine:latest AS bats-extensions
RUN apk add --no-cache git && \
    git clone --depth 1 -b v0.3.0 \
        https://github.com/bats-core/bats-support /bats/bats-support && \
    git clone --depth 1 -b v2.1.0 \
        https://github.com/bats-core/bats-assert  /bats/bats-assert && \
    git clone --depth 1 -b v1.2.5 \
        https://github.com/jasonkarns/bats-mock   /bats/bats-mock

FROM alpine:latest AS lint-tools
RUN apk add --no-cache curl xz && \
    curl -fsSL \
        https://github.com/koalaman/shellcheck/releases/download/v0.10.0/shellcheck-v0.10.0.linux.x86_64.tar.xz \
        | tar -xJ -C /tmp && \
    mv /tmp/shellcheck-v0.10.0/shellcheck /usr/local/bin/shellcheck && \
    curl -fsSL -o /usr/local/bin/hadolint \
        https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64 && \
    chmod +x /usr/local/bin/hadolint

FROM alpine:latest
COPY --from=bats-src /opt/bats /opt/bats
COPY --from=bats-src /usr/lib/bats /usr/lib/bats
COPY --from=bats-extensions /bats /usr/lib/bats
COPY --from=lint-tools /usr/local/bin/shellcheck /usr/local/bin/
COPY --from=lint-tools /usr/local/bin/hadolint /usr/local/bin/
