name: Main CI/CD Pipeline
run-name: ${{ github.actor }} triggered CI/CD on ${{ github.ref_name }}

on:
  push:
    branches:
      - main
      - master
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:

  call-docker-build:
    permissions:
      contents: read
    uses: ycpss91255-docker/template/.github/workflows/build-worker.yaml@v0.8.1
    with:
      image_name: urg_node_noetic
      build_args: |
        ROS_DISTRO=noetic
        ROS_TAG=ros-base
        UBUNTU_CODENAME=focal

  call-release:
    needs: call-docker-build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    uses: ycpss91255-docker/template/.github/workflows/release-worker.yaml@v0.8.1
    with:
      archive_name_prefix: urg_node_noetic
    secrets: inherit
